version: "3.5"

volumes:
  postgres-data:
  redis-data:

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=ttt
      - POSTGRES_PASSWORD=ttt
      - POSTGRES_DB=ttt
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    restart: always
